# Generated by Django 3.2.8 on 2021-10-30 08:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=11)),
                ('passport', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='publishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=11)),
                ('mail', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=11)),
                ('passport', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('priority', models.CharField(default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractDate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('circulation', models.IntegerField(default=0)),
                ('format', models.CharField(max_length=50)),
                ('volume', models.IntegerField(default=0)),
                ('dateExecution', models.DateField(blank=True, default=datetime.datetime.now)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishingapp.author')),
                ('publishing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishingapp.publishing')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishingapp.staff')),
            ],
        ),
    ]
